import '../../core/equipment_lab_types.dart';

/// Catálogo de comandos Teltonika para o Laboratório de Equipamentos.
///
/// Regra de transportes:
///  - Comandos `.info`, `@gps_pos`, `@chrg_info`, etc. são aceitos via porta
///    USB/serial (terminal) E via SMS (Codec 12).
///  - Comandos Codec 12 (`getparam`/`setparam`) são enviados pelo servidor FOTA;
///    **não** são aceitos via terminal serial USB diretamente → bloqueados.
///  - `.reset`, `@rec_deleteall` e comandos destrutivos exigem confirmação.
class TeltonikaCommandCatalog {
  static const List<DeviceCommandDefinition> catalog = [
    // ---- Leitura (readOnly) ------------------------------------------------
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getinfo',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640', 'FM5500', 'FMP100'],
      title: 'Informações do equipamento',
      description:
          'Retorna IMEI, modelo, firmware, hardware e versões do modem.',
      command: '.info',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'info',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getgps',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640'],
      title: 'Posição GPS',
      description: 'Força a captura de posição GNSS.',
      command: '@gps_pos',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'gps',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getcharger',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Estado da carga',
      description: 'Informações de carregamento e bateria LiPo.',
      command: '@chrg_info',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'battery',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getrecords',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640'],
      title: 'Contagem de registros',
      description: 'Número de registros AVL armazenados.',
      command: '@rec_count',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'avl',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getversion',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Versões firmware/hardware',
      description: 'Versões detalhadas (app/hardware/modem).',
      command: '@ver',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'info',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getimei',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMP100'],
      title: 'IMEI',
      description: 'IMEI de 15 dígitos do equipamento.',
      command: '@imei',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'info',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.getsn',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Número de série',
      description: 'Número de série do hardware.',
      command: '@sn',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'info',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.io',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640'],
      title: 'Estado dos IOs',
      description: 'Snapshot atual de todos os IO IDs digital/analógico.',
      command: '@io',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'io',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.cannames',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Lista de parâmetros CAN',
      description: 'Lista de parâmetros CAN disponíveis (LVCAN).',
      command: '@can_list',
      transport: [CommandTransport.usbTerminal],
      category: 'can',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.sim_status',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Estado da SIM',
      description: 'Estado e slots da SIM (AT+CPIN/AT+CCID).',
      command: '@sim',
      transport: [CommandTransport.usbTerminal],
      category: 'network',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.gprs',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140'],
      title: 'Status GPRS',
      description: 'Status da conexão de dados GPRS.',
      command: '@gprs',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'network',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.modem',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Status do modem',
      description: 'Status do modem GSM (registro/operadora).',
      command: '@modem_status',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'network',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.cwolin',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMP100'],
      title: 'Forçar saída (CWOL)',
      description: 'Aciona saída 1 (CWOL) por 1 segundo.',
      command: '@setdigout 1 1000',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'output',
      risk: RiskLevel.safe,
      requiresConfirmation: true,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.setdigout',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Acionar saída digital',
      description: 'Aciona uma saída digital por N ms.',
      command: '@setdigout',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'output',
      risk: RiskLevel.safe,
      requiresConfirmation: true,
      responseTimeoutMs: 3000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.can_mode',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Configurar modo CAN',
      description:
          'Ativa e configura o modo de leitura LV-CAN/ALL-CAN (ex: @can_mode 1 ou setparam 3000).',
      command: '@can_mode',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'can',
      risk: RiskLevel.configuration,
      requiresConfirmation: true,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.setapn',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Configurar APN',
      description:
          'Define APN, usuário e senha via terminal USB (ex: @setapn apn user pass).',
      command: '@setapn',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'configuration',
      risk: RiskLevel.configuration,
      requiresConfirmation: true,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.setserver',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902'],
      title: 'Configurar Servidor IP/Domínio',
      description:
          'Define domínio/IP e porta do servidor (ex: @setserver 1 ip port).',
      command: '@setserver',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'configuration',
      risk: RiskLevel.configuration,
      requiresConfirmation: true,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.code12getparam',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Codec 12 - Ler parâmetro',
      description: 'Lê um parâmetro via Codec 12 (getparam).',
      command: 'codec12:getparam',
      transport: [CommandTransport.tcpCodec12, CommandTransport.serverCommand],
      category: 'codec12',
      risk: RiskLevel.readOnly,
      requiresConfirmation: false,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.setparam',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Codec 12 - Escrever parâmetro',
      description:
          'Grava parâmetro via Codec 12 (setparam). Apenas FOTA/server.',
      command: 'codec12:setparam',
      transport: [CommandTransport.tcpCodec12, CommandTransport.serverCommand],
      category: 'codec12',
      risk: RiskLevel.configuration,
      requiresConfirmation: true,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.reset',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640', 'FM5500'],
      title: 'Resetar equipamento',
      description: 'Reinicia o equipamento (perde conexão temporariamente).',
      command: '.reset',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'system',
      risk: RiskLevel.destructive,
      requiresConfirmation: true,
      responseTimeoutMs: 10000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.delete_all',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMB902', 'FMC640', 'FM5500'],
      title: 'Apagar todos os registros',
      description:
          'Apagar memória de registros AVL (@rec_deleteall). Irreversível.',
      command: '@rec_deleteall',
      transport: [CommandTransport.usbTerminal, CommandTransport.sms],
      category: 'avl',
      risk: RiskLevel.destructive,
      requiresConfirmation: true,
      responseTimeoutMs: 5000,
    ),
    DeviceCommandDefinition(
      id: 'teltonika.cmd.setparam_fota',
      manufacturer: Manufacturer.teltonika,
      modelCompatibility: ['FMB140', 'FMC640'],
      title: 'Codec 12 - Atualização de firmware',
      description:
          'Upload de firmware via Codec 12 (FOTA apenas; exige confirmação dupla).',
      command: 'codec12:fw_update',
      transport: [CommandTransport.tcpCodec12, CommandTransport.serverCommand],
      category: 'firmware',
      risk: RiskLevel.destructive,
      requiresConfirmation: true,
      responseTimeoutMs: 60000,
    ),
  ];
}
